### PR TITLE
Use NeoPixelBus instead of the other ws2812 library

### PR DESCRIPTION
**Pull request by joeybab3**
Removes the extra files and such and uses neopixelbus which is supposed to be better as discussed months ago in #11

### CODE REVIEW

**Comment by joeybab3** [comment]
Sorry I'm still learning git so you get 10 commits for the files...

**Comment by Arthur266** [comment]
And what should I do after removing the files ? 
Thanks

**Comment by joeybab3** [comment]
Add the changes I've made in the main arduino sketch

**Comment by Arthur266** [comment]
And where can I see your changes ?

**Comment by Hexalyse** [comment]
Is @scottlawsonbc still maintaining this repo ? I see no activity for quite some time, and a lot of opened issues / PR.

**Comment by joeybab3** [comment]
Not sure, I was considering emailing him as it’s been months since an update and I’m willing to take over for a bit if he needs a break.

**Comment by Hexalyse** [comment]
In the meantime, I forked your own repository to use the NeoPixelBus library. 

I'm currently waiting for an Adafruit Feather Huzzah and a new 1m Led Strip (I had one but used half of it for another project) which should arrive on Monday. Then I'll try this project which seems to be the best I found.

(I was wondering something during my tests : if I lower the low frequency filter from 200Hz to let's say 20Hz, I noticed that low frequency are much "stronger" in the spectrum and thus high frequencies do not even show. 
Shouldn't it be possible not to filter out lower frequencies, but compensate for their higher volume/energy (not sure about the correct term) to get a more balanced spectrum on all the spectrum ?

I never did audio processing, but I might dwell into it to understand everythind and maybe implement other visualizations myself.)

**Comment by not-matt** [comment]
@Hexalyse I've been doing work on that kind of thing. Check out the latest issue for details.

**Comment by a-reda** [comment]
The original one didn't work for me on a WeMos D1 Mini, but this library works perfectly 👍

**Pull request merged**
