### PR TITLE
Windows loopback support

### PR DESCRIPTION
**Pull request by icecube45**
Made loopback support it's own branch as I haven't been able to compile the portaudio fork for any other os. That being said, I don't believe github supports pull requests to new branches, so pull with caution.

Added DEVICE_INDEX and USE_LOOPBACK configuration options.

I *think* I'm following pep8 correctly, let me know if I'm not.

### CODE REVIEW

**Comment by scottlawsonbc** [comment]
I've created a new branch that this can be merged into.

There appears to be a minor problem with how you are reading data from the audio stream.

In `microphone.py` you have:

```python
    stream = p.open(format=pyaudio.paInt16,
                    channels=channelcount,
```

But in `visualization.py` you are assuming that there are always two channels:

```python
    # Seperates a stereo feed into the left and right streams,
    # then pulls out the left channel for further processing
    if config.USE_LOOPBACK:
        y = np.reshape(y, (int(config.MIC_RATE / config.FPS), 2))
        y = y[:, 0]
```

It would be best to add a `channels` global variable to `microphone.py`. When `microphone.start_stream()` is called, it writes the number of channels to the global variable.

Then 
```python
y = np.reshape(y, (int(config.MIC_RATE / config.FPS), 2))
````
becomes
```python
y = np.reshape(y, (int(config.MIC_RATE / config.FPS), microphone.channels))
````

Also, you should sum the audio channels together instead of discarding the right channel. Sometimes there is useful audio information that is only present in one of the channels.

You could average the channels instead of summing, but the visualization code is volume independent so the end result is the same.

**Comment by icecube45** [comment]
Good catch there - I'll fix the channel count, and play with the two channels

**Comment by icecube45** [comment]
On the note of global variables, I'll investigate removing some configuration options, I believe I can gather the information for most of the ones I added (or modified) from just the device index.

**Comment by scottlawsonbc** [comment]
The version in master always opens the system's default audio input device. When loopback is enabled, can you make it open the default playback device?

**Comment by icecube45** [comment]
@scottlawsonbc Looks like finding the default playback device isn't as simple as I thought - I'll keep looking into it, but for now this should handle the other concerns you had.

**Comment by DurandA** [comment]
Do any of you use a loopback device on linux with this project? I believe the recommended way of doing this is using `jackaudio` but it seems a bit overkill. I wonder if using [aloop driver](https://www.alsa-project.org/main/index.php/Matrix:Module-aloop) is a good idea.

**Comment by Atraii** [comment]
I use jackaudio with d-bus. But I can't use pyaudio as it segfaults for me with JACK2. Oddly, it works fine if I'm using pulseaudio and a microphone. I have rewritten `microphone.py` to use **sounddevice**.

**Pull request merged**
