### PR TITLE
Add wifimanager

### PR DESCRIPTION
**Pull request by joeybab3**

### CODE REVIEW

**Comment by joeybab3** [comment]
This pr adds wifimanager support and reports back fps via get requests. It opens an http server on the udp port+1(ex: 7778) which can report back info such as ip or fps

**Comment by scottlawsonbc** [comment]
Thanks for the pull request. The WiFiManager code looks good, but I think there is a simpler way to implement reporting of information such as FPS. I don't think an HTTP server is necessary when it would be simpler to use the existing UDP port. I would prefer to merge the WiFiManager code separately with no other changes.

In the current version of the firmware, we can change five lines of code to report the FPS back to Python every time a packet is received.

For example, we can introduce a new variable `prevCount` to store the last known FPS value.

```arduino
uint8_t N = 0;
#if PRINT_FPS
    uint16_t fpsCounter = 0;
    uint16_t prevCount = 0;
    uint32_t secondTimer = 0;
#endif
```

When updating the FPS, we save this value to `prevCount`

```arduino
#if PRINT_FPS
    if (millis() - secondTimer >= 1000U) {
        secondTimer = millis();
        Serial.printf("FPS: %d\n", fpsCounter);
        prevCount = fpsCounter;
        fpsCounter = 0;
    }
#endif
```

Now we return the FPS value by sending a UDP ACK packet.

```arduino
#if PRINT_FPS
     fpsCounter++;    
     port.beginPacket(port.remoteIP(), port.remotePort());
     port.write(prevCount);
     port.endPacket(); 
#endif
```

On the Python side of things, it looks like this:

```python
    # Send pixel data to the ESP8266
    _sock.sendto(m, (config.UDP_IP, config.UDP_PORT))
    # Receive ACK packet from ESP8266
    data, addr = _sock.recvfrom(1024)
    # Print the FPS value that we received
    print(int.from_bytes(data, byteorder='little'))
```

Full code (omitting everything above void loop that was unchanged.

```arduino

uint8_t N = 0;
#if PRINT_FPS
    uint16_t fpsCounter = 0;
    uint16_t prevCount = 0;
    uint32_t secondTimer = 0;
#endif


void loop() {
    // Read data over socket
    int packetSize = port.parsePacket();
    // If packets have been received, interpret the command
    if (packetSize) {
        int len = port.read(packetBuffer, BUFFER_LEN);
        for(int i = 0; i < len; i+=4) {
            packetBuffer[len] = 0;
            N = packetBuffer[i];
            pixels[N].R = (uint8_t)packetBuffer[i+1];
            pixels[N].G = (uint8_t)packetBuffer[i+2];
            pixels[N].B = (uint8_t)packetBuffer[i+3];
        } 
        ledstrip.show(pixels);

        port.beginPacket(port.remoteIP(), port.remotePort());
        port.write(prevCount);
        port.endPacket();

        #if PRINT_FPS
            fpsCounter++;
        #endif
    }
    #if PRINT_FPS
        if (millis() - secondTimer >= 1000U) {
            secondTimer = millis();
            Serial.printf("FPS: %d\n", fpsCounter);
            prevCount = fpsCounter;
            fpsCounter = 0;
        }
    #endif
}
```

**Comment by joeybab3** [comment]
I was actually looking into doing a two way communication over udp type thing... I'll remake the pr without the http server

**Comment by joeybab3** [comment]
I'm not sure how to go about implementing the python part, if I pr with the arduino part, will you add it to the gui?

**Comment by scottlawsonbc** [comment]
I have been thinking more about this and have a few thoughts.

I'll outline my design philosophy for the ESP8266 firmware, because this guides my decisions about what features/changes I am willing to merge into the codebase:

**Minimal features on supported hardware**
This project started with support for the ESP8266, but has since been expanded to support the Raspberry Pi and Blinkstick, with plans for other devices in the future. Supporting multiple hardware devices can be challenging to maintain. For maintainability, it is important to have a minimal interface between Python and external hardware devices. If a hardware device such as the ESP8266 requires custom firmware, then the firmware should implement only those features which are essential to operation.

For these reasons, I am now starting to rethink whether FPS output should be included at all. Generally speaking, the ESP8266 will either *always* match the FPS of the computer, or it will be unable to keep up. If the ESP8266 can keep up then FPS output is not needed because it matches the computer. If it cannot keep up, the packet buffer will overflow and Python could be notified by sending a simple UDP ACK packet.

I am hesitant to implement other forms of communication between Python and the ESP8266 because other hardware devices are not necessarily capable of these features. I would prefer to maintain a smaller set of features that are common to all supported hardware devices.

**Comment by joeybab3** [comment]
After doing some testing on my end, I think you're right. We can keep the hardware fps debugging to just serial output. As for simplicity, I'll just work on making setup easier. I was thinking about trying to do something with mdns so that you don't even have to find the ip of the device(where I test the ip will sometimes change and i'll have to take a laptop to it). have you looked into the python mdns/zeroconf libraries?

**Comment by scottlawsonbc** [comment]
I just tried the WiFiManager code with my ESP8266. Unfortunately it does not appear to use a static IP address. This is problematic because the IP address assigned to the ESP8266 is dynamic and can change at any time. Given the nature of this project I consider a static IP to be a requirement.

Dynamic IP means that the ESP8266 will not assign itself an IP address. Instead, it will request an IP address from the router it is connecting to.  When a dynamic IP is used, the audio visualization will work fine for hours, days, or even weeks, but eventually the IP will probably change and things will stop working.

Static IP means that the ESP8266 contacts the router and declares that it is using a certain IP address. This can cause problems if [two devices claim the same static IP](http://superuser.com/questions/889602/what-happens-if-2-devices-want-the-same-static-ip-address). As long as the static IP is not already assigned to a different device, then the ESP8266's IP address will never change. 

I found a WiFiManager [example for using a static IP](https://github.com/tzapu/WiFiManager/blob/master/examples/AutoConnectWithStaticIP/AutoConnectWithStaticIP.ino), however, this example requires prior knowledge of the router's default gateway which [varies by manufacturer](http://www.techspot.com/guides/287-default-router-ip-addresses/).

Can we modify the WiFiManager code to ask the user which static IP address they would like to use?

**Comment by scottlawsonbc** [comment]
> As for simplicity, I'll just work on making setup easier. I was thinking about trying to do something with mdns so that you don't even have to find the ip of the device(where I test the ip will sometimes change and i'll have to take a laptop to it). have you looked into the python mdns/zeroconf libraries?

That is a great point. We could use Python to discover the IP of the ESP8266 with a broadcast, which would mean that it would be fine to use WiFiManager with a dynamic IP.

**Comment by scottlawsonbc** [comment]
Also, I'd be happy to merge a pull request that switches the ws2812b library to neopixelbus

**Comment by joeybab3** [comment]
We can modify the wifimanager to ask the user if they want to set the info(ip,gateway,subnet,etc) but if you want to go ahead and use the mdns/broadcast then I'll hold off on it for now(I can see some cases where that could be helpful though even with dynamic discovery)

**Comment by scottlawsonbc** [comment]
I've made a minimal example for testing network discovery:

Here is the ESP8266 firmware, and of of course change it to match your IP and network:

```arduino
#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <WebSocketsServer.h>
#include <Hash.h>
#include <WiFiUdp.h>

const char* ssid     = "YOUR-SSID-HERE";
const char* password = "YOUR-PASSWORD-HERE";
unsigned int localPort = 7777;
char packetBuffer[255];

WiFiUDP port;
IPAddress ip(192, 168, 0, 150);
IPAddress gateway(192, 168, 0, 1);
IPAddress subnet(255, 255, 255, 0);

void setup() {
    Serial.begin(115200);
    WiFi.config(ip, gateway, subnet);
    WiFi.begin(ssid, password);
    while (WiFi.status() != WL_CONNECTED) {
        delay(500);
        Serial.print(".");
    }
    Serial.print("Connected to: ");
    Serial.println(ssid);
    Serial.print("IP address: ");
    Serial.println(WiFi.localIP());
    port.begin(localPort);
}

void loop() {
  int packetSize = port.parsePacket();
  if (packetSize) {
    // Display information about packet
    Serial.print("Received packet from  ");
    IPAddress remoteIp = port.remoteIP();
    Serial.print(remoteIp);
    Serial.print(", port ");
    Serial.println(port.remotePort());
    // Read packet into buffer
    int len = port.read(packetBuffer, 255);
    if (len > 0) {
      packetBuffer[len] = 0;
    }
    Serial.println("Contents:");
    Serial.println(packetBuffer);
    // Send a reply to the packet
    port.beginPacket(port.remoteIP(), port.remotePort());
    port.write("Hello from the ESP8266");
    port.endPacket();
  }
}
```

This is a minimal Python script that sends a UDP broadcast and prints the reply. This is pretty cool because it means you could automatically detect multiple ESP8266 devices on the network and send all of them the same pixel information. Or you could use it to generate a list of ESP8266 devices and send different information to each one.

This script works on Python 3 but not Python 2.7.

```python
import time
import socket

UDP_PORT = 7777

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind(('', 0))
sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
sock.settimeout(1)

while True:

    # Send UDP broadcast
    message = 'hello from python'.encode()
    sock.sendto(message, ('<broadcast>', UDP_PORT))

    # Recieve reply
    try:
        reply, addr = sock.recvfrom(1024)
        print(reply.decode(), addr)
    except socket.timeout:
        print('No reply...')

    time.sleep(2)
```

**Comment by scottlawsonbc** [comment]
I'm merging this into a new feature branch for continuing the development of WiFi manager + UDP broadcast discovery.

**Pull request merged**
