### PR TITLE
Big Ol' Christmas Update

### PR DESCRIPTION
**Pull request by not-matt**
- New effects!
- Beat detection!
- Improved UI!
- Lots of effect settings to play with
- More modular behind the scenes makes it easy to add more effects
- Minor tweaks here and there
- Dynamic UI generation at runtime makes it easy to add UI elements

[Here's a preview](https://imgur.com/a/nMKN0)

### CODE REVIEW

**Comment by nhmann** [comment]
I am getting the following error with Version 06f775f

> File "visualization.py", line 747
    for key, label, ui_element, *opts in visualizer.dynamic_effects_config[effect]:
                                ^
SyntaxError: invalid syntax

**Comment by not-matt** [comment]
You using Python 3?

**Comment by nhmann** [comment]
My mistake: I've installed Python 2.7 and 3.4 and with 
`sudo python visualization.py` the old version is used.

Now I'm trying to do `sudo python3 visualization.py` but now:

> File "visualization.py", line 760
    self.grid_layout_widgets[effect][key] = QFloatSlider(*opts, visualizer.effect_opts[effect][key])
                                                                                       ^
SyntaxError: only named arguments may follow *expression


>

**Comment by luxxl** [comment]
It's amazing work you shared here I got it up and running on my win pc and i'm amazed by it i wanted to run it on my mac but failed and terminal is giving me errors
```
Wazaaps-MacBook-Pro:~ Lemarryuanna$ /Users/wazaap/Desktop/python/visualization.py 
from: can't read /var/mail/__future__
from: can't read /var/mail/__future__
from: can't read /var/mail/scipy.ndimage.filters
from: can't read /var/mail/collections
/Users/wazaap/Desktop/python/visualization.py: line 5: import: command not found
/Users/wazaap/Desktop/python/visualization.py: line 6: import: command not found
/Users/wazaap/Desktop/python/visualization.py: line 7: import: command not found
/Users/wazaap/Desktop/python/visualization.py: line 8: import: command not found
/Users/wazaap/Desktop/python/visualization.py: line 9: import: command not found
/Users/wazaap/Desktop/python/visualization.py: line 10: import: command not found
/Users/wazaap/Desktop/python/visualization.py: line 11: import: command not found
/Users/wazaap/Desktop/python/visualization.py: line 12: import: command not found
/Users/wazaap/Desktop/python/visualization.py: line 20: syntax error near unexpected token `('
/Users/wazaap/Desktop/python/visualization.py: line 20: `class Visualizer():'
```
I tried deleting all of python stuff as well as anaconda and reinstalled fresh version of anaconda (3.6) then got numpy scipy pyqtgraph and had to install Command Line Tools for Xcode as well as Homebrew in order to install pyaudio. Btw I'm using High Sierra 10.13.1

Sorry if I sound dumb as i'm new into it 👶  looking into any kind of help as i'm miserable atm 😄

**Comment by not-matt** [comment]
You're telling the shell to execute what it finds in the file
"visualisation.py". It's written in python, so the shell doesn't understand
any of it ("command not found").

Execute the file using python, with the following command:

python visualisation.py

(^^ Or python3 depending on your installation)

That way you're telling the shell to run Python, and passing it the file
you want to execute. Python handles the rest!


On Dec 30, 2017 01:31, "luxxl" <notifications@github.com> wrote:

It's amazing work you shared here I got it up and running on my win pc and
i'm amazed by it i wanted to run it on my mac but failed and terminal is
giving me errors

Wazaaps-MacBook-Pro:~ Lemarryuanna$
/Users/wazaap/Desktop/python/visualization.py
from: can't read /var/mail/__future__
from: can't read /var/mail/__future__
from: can't read /var/mail/scipy.ndimage.filters
from: can't read /var/mail/collections
/Users/wazaap/Desktop/python/visualization.py: line 5: import: command not found
/Users/wazaap/Desktop/python/visualization.py: line 6: import: command not found
/Users/wazaap/Desktop/python/visualization.py: line 7: import: command not found
/Users/wazaap/Desktop/python/visualization.py: line 8: import: command not found
/Users/wazaap/Desktop/python/visualization.py: line 9: import: command not found
/Users/wazaap/Desktop/python/visualization.py: line 10: import:
command not found
/Users/wazaap/Desktop/python/visualization.py: line 11: import:
command not found
/Users/wazaap/Desktop/python/visualization.py: line 12: import:
command not found
/Users/wazaap/Desktop/python/visualization.py: line 20: syntax error
near unexpected token `('
/Users/wazaap/Desktop/python/visualization.py: line 20: `class Visualizer():'

I tried deleting all of python stuff as well as anaconda and reinstalled
fresh version of anaconda (3.6) then got numpy scipy pyqtgraph and had to
install Command Line Tools for Xcode as well as Homebrew in order to
install pyaudio. Btw I'm using High Sierra 10.13.1

Sorry if I sound dumb as i'm new into it 👶 looking into any kind of help
as i'm miserable atm 😄

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/scottlawsonbc/audio-reactive-led-strip/pull/101#issuecomment-354520210>,
or mute the thread

**Comment by luxxl** [comment]
Oh, thank you! Well that was dumb mistake from me but I blame apple for that 🙉 🤣

**Comment by not-matt** [comment]
No worries. I've yet to hear about how my update runs on macOS, so do let
me know about any bugs etc.

Enjoy!

**Comment by luxxl** [comment]
Talking about my mac's hardware got to give credit to dual core i5 as I can make fps adjustments on fly only by resizing visualization window 🤣 the bigger window is the less fps it's doing (full screen 60 fps) it's a feature! 😆  

Visualization looks wonderful, i really like new effects and UI looks nice. So far no mayor bugs. Only few thing I noticed. Sometimes LED's transition slows down but I doubt it's script problem as it runs at ~160 fps (144 target) at moment of stuttering (I think it might be my router fault handling packets in time). Second thing is that when you select one effect and then other it's stays highlighted but it's not a real problem.

I'm not sure know how to express what I would like to suggest you as I'm not native English speaker but i will try.
It would be very interesting to see something like variable length effects. What i mean by that is some kind of few effects merging into one led strip in attempt to use one controller to control two strips so as example can run 100 led's with scroll effect, another 100 with bars effect and another 50 with beat effect just from one data line. As my knowledge is very limited I can't tell how difficult it would be but I think it would be super cool to have. 

Overall I'm amazed by your work and really like those new effects especially those sparkles. ✨ I have something like party speaker prototype built around JBL EON 15 G2 and it looks amazing even only with LED strip around it and it's fun at parties as not not only it packs a punch but lot of nice effects. 

Till the summer I'm planing to make custom cabinet speakers so I could implement LED's as I want where I want them with different effects running at once like I said before. Even if I will end up using multiple esp's and multiple scripts running at once but end result should look bananaz 🍌

**Comment by not-matt** [comment]
Dude I'm glad you like it! I have yet to see the "Power" effect on an
actual strip, since I've written most of the new ones since coming home
from university. Any chance you could record it and stick it on
streamable/yt?

One thing in future will be multiple strip support in the same instance of
the program, but for now yeah running multiple instances will have to do.

With regards to multiple effects on the same strip, I think that could be
possible, but it will have to be after multiple strip support is put into
place.

I'll see if I can fix that highlighting thing too, cheers for pointing that
out!


On Dec 30, 2017 23:06, "luxxl" <notifications@github.com> wrote:

Talking about my mac's hardware got to give credit to dual core i5 as I can
make fps adjustments on fly only by resizing visualization window 🤣 the
bigger window is the less fps it's doing (full screen 60 fps) it's a
feature! 😆

Visualization looks wonderful, i really like new effects and UI looks nice.
So far no mayor bugs. Only few thing I noticed. Sometimes LED's transition
slows down but I doubt it's script problem as it runs at ~160 fps (144
target) at moment of stuttering (I think it might be my router fault
handling packets in time). Second thing is that when you select one effect
and then other it's stays highlighted but it's not a real problem.

I'm not sure know how to express what I would like to suggest you as I'm
not native English speaker but i will try.
It would be very interesting to see something like variable length effects.
What i mean by that is some kind of few effects merging into one led strip
in attempt to use one controller to control two strips so as example can
run 100 led's with scroll effect, another 100 with bars effect and another
50 with beat effect just from one data line. As my knowledge is very
limited I can't tell how difficult it would be but I think it would be
super cool to have.

Overall I'm amazed by your work and really like those new effects
especially those sparkles. ✨ I have something like party speaker prototype
built around JBL EON 15 G2 and it looks amazing even only with LED strip
around it and it's fun at parties as not not only it packs a punch but lot
of nice effects.

Till the summer I'm planing to make custom cabinet speakers so I could
implement LED's as I want where I want them with different effects running
at once like I said before. Even if I will end up using multiple esp's and
multiple scripts running at once but end result should look bananaz 🍌

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/scottlawsonbc/audio-reactive-led-strip/pull/101#issuecomment-354573663>,
or mute the thread

**Comment by luxxl** [comment]
Here you go [https://streamable.com/69o3b](url)

**Comment by not-matt** [comment]
@nhmann By the way, I wouldn't recommend using sudo to run this program. In general, unless you know the program explicitely needs root permissions, it is not a great idea to go handing it out. Is there an issue with this that requires a sudo to fix? (eg firewall or something along those lines)

**Comment by nhmann** [comment]
@not-matt no, thank you for your tip. Do you have any ideas for my Problem?

>   File "visualization.py", line 760
    self.grid_layout_widgets[effect][key] = QFloatSlider(*opts, visualizer.effect_opts[effect][key])
                                                                                       ^
SyntaxError: only named arguments may follow *expression

**Comment by not-matt** [comment]
What version of Python are you using? It works fine for me, using 3.6.2. Run Python, it says just above the prompt.

**Comment by nhmann** [comment]
I am using 3.4.2. I am going to update it an will report the result, give me a few minutes.
Thanks for your great help!

**Comment by nhmann** [comment]
@not-matt Okay, it turned out that to clean up my system and to reinstall everything was the better idea. So my "a few minutes" action was a "four hour" action.

My latest error this your version:

> Traceback (most recent call last):
  File "visualization.py", line 11, in <module>
    import led
  File "/home/pi/audio-reactive-led-strip/python/led.py", line 34, in <module>
    import neopixel
ImportError: No module named 'neopixel'

**Comment by not-matt** [comment]
If you are using a Raspberry Pi for audio processing, do "sudo pip install neopixel". Depending on your installation, it may be pip3, for Python 3.

**Comment by nhmann** [comment]
Still no luck:

> Traceback (most recent call last):
  File "/home/pi/audio-reactive-led-strip/python/visualization.py", line 11, in <module>
    import led
  File "/home/pi/audio-reactive-led-strip/python/led.py", line 38, in <module>
    strip.begin()
  File "/usr/local/lib/python3.5/dist-packages/rpi_ws281x-1.0.0-py3.5-linux-armv7l.egg/neopixel.py", line 106, in begin
    raise RuntimeError('ws2811_init failed with code {0} ({1})'.format(resp, message))
RuntimeError: ws2811_init failed with code -5 (mmap() failed)

**Comment by not-matt** [comment]
After looking at [this discussion](
https://github.com/jgarff/rpi_ws281x/issues/155) it seems like you need
root permissions to allocate some memory. Try running with sudo.

When I said earlier about not needing sudo, I didn't realise there was an
explicit reason for using it. Seems like there is, so this is a good time
to use it after all!

**Comment by nhmann** [comment]
Okay, after the latest problems i decided to reinstall Raspbian and go from 0.
This time i noticed every step.
My new error :smile::

> libEGL warning: DRI2: failed to authenticate
Traceback (most recent call last):
  File "visualization.py", line 967, in <module>
    led.update()
  File "/home/pi/audio-reactive-led-strip/python/led.py", line 163, in update
    _update_pi()
  File "/home/pi/audio-reactive-led-strip/python/led.py", line 127, in _update_pi
    strip._led_data[i] = rgb[i]
  File "/usr/local/lib/python3.5/dist-packages/rpi_ws281x-1.0.0-py3.5-linux-armv7l.egg/neopixel.py", line 49, in __setitem__
    return ws.ws2811_led_set(self.channel, pos, value)
TypeError: in method 'ws2811_led_set', argument 3 of type 'uint32_t'


# My installation:
## 1. Update System

> sudo apt-get update
sudo apt-get upgrade

## 2. install ws281x library
> sudo apt-get install python3-numpy python3-scipy python3-pyaudio
sudo apt-get install build-essential python3-dev git scons swig
git clone https://github.com/jgarff/rpi_ws281x.git
cd rpi_ws281x
scons
cd python
sudo python3 setup.py install


### testing
> cd rpi_ws281x/python/examples
sudo python strandtest.py

## 3. change audio settings
> sudo nano /etc/asound.conf

### add
> pcm.!default {
    type hw
    card 1
}
ctl.!default {
    type hw
    card 1
}

### save, exit

> sudo nano /usr/share/alsa/alsa.conf

### change
> defaults.ctl.card 0
defaults.pcm.card 0

### to
> defaults.ctl.card 1
defaults.pcm.card 1

### change the raspberry audio settings
> Settings --> Audio Device Settings --> Sound Card --> "Choose USB Soundcard"  --> Select Elements --> Speaker, Microfone, Microfone Recording

## 4. install pyqtgraph:
> git clone https://github.com/pyqtgraph/pyqtgraph.git
cd pyqtgraph
sudo python3 setup.py install
cd

## 5. install audio-reactive-led-strip:
> git clone https://github.com/scottlawsonbc/audio-reactive-led-strip.git
cd audio-reactive-led-strip/python

### run it
> sudo python3 visualization.py

**Comment by not-matt** [comment]
Try following the guide in [this faq](https://pi3d.github.io/html/FAQ.html#glx-dri2-not-supported-or-failed-to-authenticate), it seems to be an issue with Raspbian. [This GitHub issue thread](https://github.com/tipam/pi3d/issues/177) also discusses your problem, but I'm not sure they resolved it.

Has anyone else had success using a Raspberry Pi?

**Comment by nhmann** [comment]
Okay, thanks for your fast feedback, next error :smile::

> Traceback (most recent call last):
  File "visualization.py", line 14, in <module>
    from qrangeslider import QRangeSlider
  File "/home/pi/audio-reactive-led-strip/python/qrangeslider.py", line 2, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: libGLESv2.so.2: cannot open shared object file: No such file or directory

**Comment by not-matt** [comment]
Good lord... We'll get there eventually! Have a look at [this answer](https://stackoverflow.com/questions/1099981/why-cant-python-find-shared-objects-that-are-in-directories-in-sys-path#1100016) on StackOverflow. [This one](https://stackoverflow.com/questions/44294396/importerror-libsasl2-so-3-cannot-open-shared-object-file-no-such-file-or-dire) is similar. Best of luck!

**Comment by nhmann** [comment]
Hey back, it turned out that PyQt5 wasn't installed (the installation guide is missing infos sometimes)
`sudo apt-get install qt5-default pyqt5-dev pyqt5-dev-tools`
When it finally works, we need to fix the raspberry installation guide.

New error:

> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 426, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: unpickling stack underflow

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "visualization.py", line 11, in <module>
    import led
  File "/home/pi/audio-reactive-led-strip/python/led.py", line 54, in <module>
    _gamma = np.load(config.GAMMA_TABLE_PATH)
  File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 429, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file '/home/pi/audio-reactive-led-strip/python/gamma_table.npy' as a pickle

Is it a step in the right direction or thre steps back?

**Comment by nhmann** [comment]
@not-matt i found this: [https://stackoverflow.com/questions/19793937/failed-to-interpret-file-s-as-a-pickle-when-loading-an-npy-array](https://stackoverflow.com/questions/19793937/failed-to-interpret-file-s-as-a-pickle-when-loading-an-npy-array)

**Comment by not-matt** [comment]
Never seen that before, try making changes as suggested in that answer.

**Comment by TheDutchDevil** [comment]
Does this still break non Pi setups?

**Comment by luxxl** [comment]
Man I love this! You are true MVP here 💯 I was about to share interesting experience with setting up that i couldn't configure static ip's so I changed it to false and while typing this I released I mixed up my router's ip with desired esp ip jokes on me. Still love your work <3

**Comment by Zyqmen** [comment]
Thank you! Awesome project.
https://www.youtube.com/watch?v=xPgSE5FUAac

**Comment by JanJurre** [comment]
Wauw this looks like a lovely update! But how do I get alle the correct files and make it work? (NodeMCU and windows pc)

Thanks in advance!

**Comment by not-matt** [comment]
@JanJurre 
Download this pull request and run it. For setting up your nodemcu, the process is outlined on the guide on this project's main page.
Let me know if you run into any difficulties along the way.

**Comment by JanJurre** [comment]
@not-matt  Got it man! Thank you!

**Comment by not-matt** [comment]
Awesome! Join this discord for updates and development

https://discord.gg/F5AqZkv

**Comment by joeybab3** [comment]
Thanks for the updates matt! I see you've created your own repo now for it so I'll close this PR to avoid confusion.

**Pull request closed without merging**
