### PR TITLE
BlinkstickPro support

### PR DESCRIPTION
**Pull request by kevinkellner**
I have added support for the Blinkstick Pro. 
Let me know if I need to change something else and I will try to.

### CODE REVIEW

**Comment by scottlawsonbc** [comment]
This looks great! I do not have a Blinkstick so I am unable to test this myself. Have you been able to test this? Can you confirm that this code works on Python 2.7 and Python 3.5?

**Comment by kevinkellner** [comment]
Python 2.7 works for me. Python 3.5 needs another change as Python3 does not have the 'long' datatype anymore. It needs to be changed to 'int'. 
I have also changed it in the raspberry pi version. It should work for both Python 2.7 and 3.5 now.

**Comment by scottlawsonbc** [comment]
Just for my own curiosity, I'd be interested in knowing a bit more about your setup. Are you using a Raspberry Pi or desktop/laptop? Are you happy with how the effects look?

I'm impressed that you added support for the blinkstrip only an hour after forking the repo. Was there anything that you found confusing about the code or documentation? I'm always looking for things that could be improved.

I tried to organize the code so that it would be easy to add support for other hardware. The `visualization.py` module makes no assumptions about the underlying hardware, so adding support for other decives just requires you to implement a hardware-specific function the `led.py` module. It looks like you were able to figure that out very quickly even though it isn't documented.

**Comment by kevinkellner** [comment]
I am using a normal desktop, running Arch Linux. The Blinkstick is connected directly to the PC. I attached it to the back of my desk, so that it can light up the wall behind it. If you are interested I could upload a video tomorrow.
It looks really nice. Thanks for all your work. 

It took me longer than one hour. I cloned the repo first and after I was almost done I realized that other people could benefit, so I forked the repo, organized the commits a bit better and sent the pull request.
It helps that I worked with the Blinkstick a bit before that.

But the code was easy to understand. I just needed to look at the visualization.py and led.py modules. Also I could use the raspberry pi code as inspiration. So it was not that hard.

**Comment by scottlawsonbc** [comment]
Thanks for the information and feedback. Although I don't own a blinkstick, the circuit seems very simple and I happen to have the components needed to make one. I'll prototype one this weekend and give your code a try before merging the pull request.

I like your idea of turning the LED strip off using a signal handler. Assuming it works then we should use that for all devices and not just the blinkstick.

**Comment by scottlawsonbc** [comment]
Unfortunately I haven't had time to test a blinkstick yet. Have you encountered any problems?

**Comment by kevinkellner** [comment]
I have not yet had any problems. It works fine for me.

**Pull request merged**
