### PR TITLE
Added FPS output

### PR DESCRIPTION
**Pull request by joeybab3**
Also shows if its connected successfully

### CODE REVIEW

**Comment by scottlawsonbc** [comment]
Thanks for your pull request. I'm open to merging this but I think it would be best to make a couple of other changes at the same time.

The firmware has some code that I added to toggle an IO pin:
```
pinMode(0, OUTPUT);
...
digitalWrite(0, 1);
digitalWrite(0, 0);
```

I originally added this code so that I could use my oscilloscope to observe the IO pin and measure the FPS. Your pull request makes this obsolete, so it would be best to remove the `pinMode` and `digitalWrite` calls.

Could you also add a define macro to configure whether FPS should be printed?
Something like:

```
#define PRINT_FPS
```

```
#ifdef PRINT_FPS
if(millis() - secondTimer >= 1000)
 +  {
 +    secondTimer = millis();
 +
 +    Serial.printf("FPS: %d\n", fpsCounter);
 +    fpsCounter = 0;
 +  }
#endif
```

If you could make these changes I'd be happy to merge the pull request.

**Comment by joeybab3** [comment]
done as requested :)

**Comment by scottlawsonbc** [comment]
```
#ifdef PRINT_FPS
```
This conditional statement above will check whether `PRINT_FPS` is defined. It does not check to see if a value is associated with `PRINT_FPS`. This means that `#ifdef PRINT_FPS` will be true in all of the cases below:
```
#define PRINT_FPS
#define PRINT_FPS 1
#define PRINT_FPS 0
```

If you use `PRINT_FPS 0` and `PRINT_FPS 1` to toggle the FPS output, then you need to replace `#ifdef PRINT_FPS` with `#if PRINT_FPS`.

Also, I think it would be best to include the `Serial.print("*");` inside the conditional statement. If the user sets `PRINT_FPS 0` then the ESP8266 should not print anything to the serial port.

**Comment by joeybab3** [comment]
Alright, let me know what you think

**Pull request merged**
